"use client";

import { useQuery } from "@tanstack/react-query";
import { motion } from "motion/react";
import { AlertTriangle, ArrowLeft, Check, CircleAlert, Minus } from "lucide-react";
import Link from "next/link";
import { use } from "react";

import { Skeleton } from "@/components/ui/skeleton";
import { api, qk } from "@/lib/api";
import { cn } from "@/lib/utils";

export default function SymbolReport({ params }: { params: Promise<{ symbol: string }> }) {
  // Next 16 hands route params as a promise; `use` unwraps it in a client component.
  const { symbol: raw } = use(params);
  const symbol = decodeURIComponent(raw).toUpperCase();

  const report = useQuery({
    queryKey: qk.report(symbol),
    queryFn: ({ signal }) => api.report(symbol, signal),
  });
  const card = useQuery({
    queryKey: qk.scorecard(symbol),
    queryFn: ({ signal }) => api.scorecard(symbol, signal),
  });
  const qs = useQuery({
    queryKey: qk.questions(symbol),
    queryFn: ({ signal }) => api.questions(symbol, signal),
  });

  return (
    <div className="space-y-4 p-4 md:p-6">
      <Link
        href="/admin/swing-pro"
        className="inline-flex items-center gap-1.5 text-[12px] text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="size-3.5" /> All symbols
      </Link>

      <div className="flex items-baseline gap-3">
        <h2 className="font-mono text-xl font-semibold tracking-tight">{symbol}</h2>
        {card.data && (
          <span className="font-mono text-[13px] text-muted-foreground">
            {card.data.total}/100 · {card.data.grade}
          </span>
        )}
      </div>

      {report.isError && (
        <div className="flex items-start gap-3 rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-[13px]">
          <CircleAlert className="mt-0.5 size-4 shrink-0 text-destructive" />
          <div className="text-muted-foreground">{(report.error as Error).message}</div>
        </div>
      )}

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.6fr)_minmax(0,1fr)]">
        {/* The report is rendered as-is, monospace. It is generated by Python in the framework's
            exact Section 22 order, and re-laying it out in React would be a second implementation
            of the thing most likely to drift. */}
        <section className="min-w-0 rounded-lg border border-border bg-card">
          <h3 className="border-b border-border px-4 py-2.5 text-[13px] font-semibold tracking-tight">
            The 22-section report
          </h3>
          {report.isPending ? (
            <div className="space-y-2 p-4">
              {Array.from({ length: 14 }).map((_, i) => (
                <Skeleton key={i} className="h-4 w-full" />
              ))}
            </div>
          ) : (
            <pre className="overflow-x-auto p-4 font-mono text-[11.5px] leading-[1.65] text-foreground/90">
              {report.data?.text}
            </pre>
          )}
        </section>

        <div className="space-y-4">
          <section className="rounded-lg border border-border bg-card">
            <h3 className="border-b border-border px-4 py-2.5 text-[13px] font-semibold tracking-tight">
              Section 20 — the 100-point scorecard
            </h3>
            <div className="space-y-2.5 p-4">
              {card.isPending
                ? Array.from({ length: 10 }).map((_, i) => <Skeleton key={i} className="h-6" />)
                : card.data?.parts.map((p, i) => (
                    <div key={p.name} className="space-y-1">
                      <div className="flex items-baseline justify-between gap-2 text-[12px]">
                        <span className="truncate text-muted-foreground">{p.name}</span>
                        <span className="shrink-0 font-mono tabular-nums">
                          {p.got}
                          <span className="text-muted-foreground">/{p.max}</span>
                        </span>
                      </div>
                      <div className="h-1 overflow-hidden rounded-full bg-muted">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${(p.got / p.max) * 100}%` }}
                          transition={{ delay: i * 0.03, duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
                          className={cn(
                            "h-full rounded-full",
                            p.got / p.max >= 0.75
                              ? "bg-up"
                              : p.got / p.max >= 0.4
                                ? "bg-primary"
                                : "bg-muted-foreground/50",
                          )}
                        />
                      </div>
                    </div>
                  ))}
            </div>
          </section>

          <section className="rounded-lg border border-border bg-card">
            <h3 className="border-b border-border px-4 py-2.5 text-[13px] font-semibold tracking-tight">
              Section 21 — the fifteen questions
            </h3>
            <div className="divide-y divide-border/60">
              {qs.isPending
                ? Array.from({ length: 15 }).map((_, i) => (
                    <Skeleton key={i} className="m-3 h-5" />
                  ))
                : qs.data?.answers.map((a) => {
                    const warn = qs.data.warning_questions.includes(a.n);
                    return (
                      <div key={a.n} className="flex items-start gap-2.5 px-4 py-2">
                        <Verdict answer={a.answer} warn={warn} />
                        <div className="min-w-0 text-[12px] leading-snug">
                          <span className="text-muted-foreground">{a.question}</span>
                          {a.kind === "text" && (
                            <div className="mt-0.5 text-foreground">{String(a.answer)}</div>
                          )}
                          {warn && (
                            <span className="ml-1 font-mono text-[10px] uppercase text-primary">
                              yes = bad
                            </span>
                          )}
                        </div>
                      </div>
                    );
                  })}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

/**
 * Q9 is inverted on purpose — "is the stock already too extended to enter safely?", where YES is
 * the warning. Rendering it as a green tick would invert the meaning of the question, which is a
 * regression this framework has actually shipped before.
 */
function Verdict({ answer, warn }: { answer: boolean | string; warn: boolean }) {
  if (typeof answer === "string") {
    return <Minus className="mt-0.5 size-3.5 shrink-0 text-muted-foreground" />;
  }
  if (warn) {
    return answer ? (
      <AlertTriangle className="mt-0.5 size-3.5 shrink-0 text-primary" />
    ) : (
      <Check className="mt-0.5 size-3.5 shrink-0 text-up" />
    );
  }
  return answer ? (
    <Check className="mt-0.5 size-3.5 shrink-0 text-up" />
  ) : (
    <Minus className="mt-0.5 size-3.5 shrink-0 text-muted-foreground" />
  );
}
